require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FileLinksController do

  # This should return the minimal set of attributes required to create a valid
  # FileLink. As you add validations to FileLink, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "type" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FileLinksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all file_links as @file_links" do
      file_link = FileLink.create! valid_attributes
      get :index, {}, valid_session
      assigns(:file_links).should eq([file_link])
    end
  end

  describe "GET show" do
    it "assigns the requested file_link as @file_link" do
      file_link = FileLink.create! valid_attributes
      get :show, {:id => file_link.to_param}, valid_session
      assigns(:file_link).should eq(file_link)
    end
  end

  describe "GET new" do
    it "assigns a new file_link as @file_link" do
      get :new, {}, valid_session
      assigns(:file_link).should be_a_new(FileLink)
    end
  end

  describe "GET edit" do
    it "assigns the requested file_link as @file_link" do
      file_link = FileLink.create! valid_attributes
      get :edit, {:id => file_link.to_param}, valid_session
      assigns(:file_link).should eq(file_link)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FileLink" do
        expect {
          post :create, {:file_link => valid_attributes}, valid_session
        }.to change(FileLink, :count).by(1)
      end

      it "assigns a newly created file_link as @file_link" do
        post :create, {:file_link => valid_attributes}, valid_session
        assigns(:file_link).should be_a(FileLink)
        assigns(:file_link).should be_persisted
      end

      it "redirects to the created file_link" do
        post :create, {:file_link => valid_attributes}, valid_session
        response.should redirect_to(FileLink.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved file_link as @file_link" do
        # Trigger the behavior that occurs when invalid params are submitted
        FileLink.any_instance.stub(:save).and_return(false)
        post :create, {:file_link => { "type" => "invalid value" }}, valid_session
        assigns(:file_link).should be_a_new(FileLink)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FileLink.any_instance.stub(:save).and_return(false)
        post :create, {:file_link => { "type" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested file_link" do
        file_link = FileLink.create! valid_attributes
        # Assuming there are no other file_links in the database, this
        # specifies that the FileLink created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FileLink.any_instance.should_receive(:update).with({ "type" => "" })
        put :update, {:id => file_link.to_param, :file_link => { "type" => "" }}, valid_session
      end

      it "assigns the requested file_link as @file_link" do
        file_link = FileLink.create! valid_attributes
        put :update, {:id => file_link.to_param, :file_link => valid_attributes}, valid_session
        assigns(:file_link).should eq(file_link)
      end

      it "redirects to the file_link" do
        file_link = FileLink.create! valid_attributes
        put :update, {:id => file_link.to_param, :file_link => valid_attributes}, valid_session
        response.should redirect_to(file_link)
      end
    end

    describe "with invalid params" do
      it "assigns the file_link as @file_link" do
        file_link = FileLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FileLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => file_link.to_param, :file_link => { "type" => "invalid value" }}, valid_session
        assigns(:file_link).should eq(file_link)
      end

      it "re-renders the 'edit' template" do
        file_link = FileLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FileLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => file_link.to_param, :file_link => { "type" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested file_link" do
      file_link = FileLink.create! valid_attributes
      expect {
        delete :destroy, {:id => file_link.to_param}, valid_session
      }.to change(FileLink, :count).by(-1)
    end

    it "redirects to the file_links list" do
      file_link = FileLink.create! valid_attributes
      delete :destroy, {:id => file_link.to_param}, valid_session
      response.should redirect_to(file_links_url)
    end
  end

end
